version: '3.8'

services:
  eureka-server:
    image: eureka-server:latest
    container_name: eureka-server
    hostname: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices-network

  api-gateway:
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "8765:8765"
    depends_on:
      - eureka-server
    networks:
      - microservices-network

  product-service:
    image: product-service:latest
    container_name: product-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.H2Dialect
      - EUREKA_CLIENT_SERVICE_URL=http://eureka-server:8761/eureka
    networks:
      - microservices-network

  order-service:
    image: order-service:latest
    container_name: order-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.H2Dialect
      - EUREKA_CLIENT_SERVICE_URL=http://eureka-server:8761/eureka
    networks:
      - microservices-network

  customer-service:
    image: customer-service:latest
    container_name: customer-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.H2Dialect
      - EUREKA_CLIENT_SERVICE_URL=http://eureka-server:8761/eureka
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge